

-- TheHealthy 계정 생성
-- CREATE USER TheHealthy IDENTIFIED BY TheHealthy;
-- GRANT RESOURCE, CONNECT TO TheHealthy;
-- 계정 삭제하기
-- drop user TheHealthy cascade;


-----------------------------------------------------------------------------------------------------------------------------------------------------------
--------------- HEALTHYRECIPE 관련 테이블 ---------------
-----------------------------------------------------------------------------------------------------------------------------------------------------------


DROP TABLE HEALTHRECIPE CASCADE CONSTRAINTS;
CREATE TABLE HEALTHRECIPE (
    HR_NO NUMBER PRIMARY KEY,
    RCP_NM VARCHAR2(200),
    RCP_PAT2 VARCHAR2(50),
    RCP_WAY2 VARCHAR2(50),
    INFO_WGT VARCHAR2(20),
    INFO_ENG NUMBER,
    INFO_CAR VARCHAR2(20),
    INFO_PRO VARCHAR2(20),
    INFO_FAT VARCHAR2(20),
    INFO_NA VARCHAR2(20),
    ATT_FILE_NO_MK VARCHAR2(900),
    RCP_PARTS_DTLS CLOB
);

COMMENT ON COLUMN HEALTHRECIPE.HR_NO IS '일련번호';
COMMENT ON COLUMN HEALTHRECIPE.RCP_NM IS '메뉴명';
COMMENT ON COLUMN HEALTHRECIPE.RCP_WAY2 IS '조리방법';
COMMENT ON COLUMN HEALTHRECIPE.RCP_PAT2 IS '요리종류';
COMMENT ON COLUMN HEALTHRECIPE.INFO_WGT IS '중량(1인분)';
COMMENT ON COLUMN HEALTHRECIPE.INFO_ENG IS '열량';
COMMENT ON COLUMN HEALTHRECIPE.INFO_CAR IS '탄수화물';
COMMENT ON COLUMN HEALTHRECIPE.INFO_PRO IS '단백질';
COMMENT ON COLUMN HEALTHRECIPE.INFO_FAT IS '지방';
COMMENT ON COLUMN HEALTHRECIPE.INFO_NA IS '나트륨';
COMMENT ON COLUMN HEALTHRECIPE.ATT_FILE_NO_MK IS '이미지경로(대)';
COMMENT ON COLUMN HEALTHRECIPE.RCP_PARTS_DTLS IS '재료정보';

COMMIT;


-----------------------------------------------------------------------------------------------------------------------------------------------------------
--------------- RECIPEMANUAL 관련 테이블 ---------------
-----------------------------------------------------------------------------------------------------------------------------------------------------------


DROP TABLE RECIPEMANUAL CASCADE CONSTRAINTS;
CREATE TABLE RECIPEMANUAL (
    RM_NO NUMBER PRIMARY KEY,
    HR_NO NUMBER,
    SEQ NUMBER,
    manual VARCHAR2(900),
    manualImg VARCHAR2(900),
    FOREIGN KEY(HR_NO) REFERENCES HEALTHRECIPE(HR_NO)
);

COMMENT ON COLUMN RECIPEMANUAL.RM_NO IS '일련번호';
COMMENT ON COLUMN RECIPEMANUAL.HR_NO IS 'HEALTHYRECIPE 일련번호';
COMMENT ON COLUMN RECIPEMANUAL.SEQ IS '만드는 순서';
COMMENT ON COLUMN RECIPEMANUAL.manual IS '만드는 법';
COMMENT ON COLUMN RECIPEMANUAL.manualImg IS '이미지경로';

DROP SEQUENCE SEQ_RECIPEMANUAL;
CREATE SEQUENCE SEQ_RECIPEMANUAL;

COMMIT;


-----------------------------------------------------------------------------------------------------------------------------------------------------------
--------------- HEALTHSEASON 관련 테이블 ---------------
-----------------------------------------------------------------------------------------------------------------------------------------------------------


DROP TABLE HEALTHSEASON CASCADE CONSTRAINTS;
CREATE TABLE HEALTHSEASON (
    HS_NO NUMBER PRIMARY KEY,
    PRDLST_NM VARCHAR2(800),
    M_DISTCTNS VARCHAR2(50),
    MTC_NM VARCHAR2(200),
    EFFECT VARCHAR2(700),
    PURCHASE_MTH VARCHAR2(900),
    COOK_MTH CLOB,
    TRT_MTH VARCHAR2(800),
    IMG_URL VARCHAR2(800)
);

COMMENT ON COLUMN HEALTHSEASON.HS_NO IS '일련번호';
COMMENT ON COLUMN HEALTHSEASON.PRDLST_NM IS '품목명';
COMMENT ON COLUMN HEALTHSEASON.M_DISTCTNS IS '월별';
COMMENT ON COLUMN HEALTHSEASON.MTC_NM IS '주요산지';
COMMENT ON COLUMN HEALTHSEASON.EFFECT IS '효능';
COMMENT ON COLUMN HEALTHSEASON.PURCHASE_MTH IS '구입요령';
COMMENT ON COLUMN HEALTHSEASON.COOK_MTH IS '조리법';
COMMENT ON COLUMN HEALTHSEASON.TRT_MTH IS '손질요령';
COMMENT ON COLUMN HEALTHSEASON.IMG_URL IS '이미지';

DROP SEQUENCE SEQ_HEALTHSEASON;
CREATE SEQUENCE SEQ_HEALTHSEASON;

COMMIT;


-----------------------------------------------------------------------------------------------------------------------------------------------------------
--------------- HEALTHFOOD 관련 테이블 ---------------
-----------------------------------------------------------------------------------------------------------------------------------------------------------


 DROP TABLE HEALTHFOOD CASCADE CONSTRAINTS;
 CREATE TABLE HEALTHFOOD(
    HF_NO NUMBER PRIMARY KEY,
    PRDCT_NM  VARCHAR2(200),
    IFTKN_ATNT_MATR_CN CLOB,
    PRIMARY_FNCLTY  VARCHAR2(500),
    DAY_INTK_LOWLIMIT  VARCHAR2(200),
    DAY_INTK_HIGHLIMIT  VARCHAR2(200),
    INTK_UNIT  VARCHAR2(200),
    SKLL_IX_IRDNT_RAWMTRL  VARCHAR2(300)
);

DROP SEQUENCE SEQ_HEALTHFOOD;
CREATE SEQUENCE SEQ_HEALTHFOOD;

COMMIT;



------------------------------------------------
--------------- Board 관련 테이블 ---------------
------------------------------------------------


DROP TABLE FREEBOARD CASCADE CONSTRAINTS;
CREATE TABLE FREEBOARD (	
    NO NUMBER,
    WRITER_NO NUMBER, 
	TITLE VARCHAR2(50), 
	CONTENT VARCHAR2(2000), 
	ORIGINAL_FILENAME VARCHAR2(100), 
	RENAMED_FILENAME VARCHAR2(100), 
	READCOUNT NUMBER DEFAULT 0, 
    STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN('Y', 'N')),
    CREATE_DATE DATE DEFAULT SYSDATE, 
    MODIFY_DATE DATE DEFAULT SYSDATE,
    CONSTRAINT PK_BOARD_NO PRIMARY KEY(NO),
    CONSTRAINT FK_BOARD_WRITER FOREIGN KEY(WRITER_NO) REFERENCES MEMBER(NO) ON DELETE SET NULL
);

COMMENT ON COLUMN FREEBOARD.NO IS '게시글번호';
COMMENT ON COLUMN FREEBOARD.WRITER_NO IS '게시글작성자';
COMMENT ON COLUMN FREEBOARD.TITLE IS '게시글제목';
COMMENT ON COLUMN FREEBOARD.CONTENT IS '게시글내용';
COMMENT ON COLUMN FREEBOARD.ORIGINAL_FILENAME IS '첨부파일원래이름';
COMMENT ON COLUMN FREEBOARD.RENAMED_FILENAME IS '첨부파일변경이름';
COMMENT ON COLUMN FREEBOARD.READCOUNT IS '조회수';
COMMENT ON COLUMN FREEBOARD.STATUS IS '상태값(Y/N)';
COMMENT ON COLUMN FREEBOARD.CREATE_DATE IS '게시글올린날짜';
COMMENT ON COLUMN FREEBOARD.MODIFY_DATE IS '게시글수정날짜';

DROP SEQUENCE SEQ_BOARD_NO;
CREATE SEQUENCE SEQ_BOARD_NO;

INSERT INTO FREEBOARD VALUES(SEQ_BOARD_NO.NEXTVAL,1,'자유게시판이머에요?','이거 어떻게 쓰는거에요?',NULL,NULL,DEFAULT,'Y',SYSDATE,SYSDATE);
INSERT INTO FREEBOARD VALUES(SEQ_BOARD_NO.NEXTVAL,1,'이게 맞는건가','글이 올라 가긴 하는건가',NULL,NULL,DEFAULT,'Y',SYSDATE,SYSDATE);
INSERT INTO FREEBOARD VALUES(SEQ_BOARD_NO.NEXTVAL,1,'식단말인데요','몸무게를 줄이고 싶은데 어떻게 하면 좋을까요??',NULL,NULL,DEFAULT,'Y',SYSDATE,SYSDATE);
INSERT INTO FREEBOARD VALUES(SEQ_BOARD_NO.NEXTVAL,1,'제가 몸무게 40kg 뺐던식단공유합니다','그런건 없어요 열심히 운동하세요','거짓말.txt',NULL,DEFAULT,'Y',SYSDATE,SYSDATE);
INSERT INTO FREEBOARD VALUES(SEQ_BOARD_NO.NEXTVAL,1,'운동중에 가장 제일 좋은 운동은?','잘먹고 운동많이 하기 ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ',NULL,NULL,DEFAULT,'Y',SYSDATE,SYSDATE);
INSERT INTO FREEBOARD VALUES(SEQ_BOARD_NO.NEXTVAL,1,'황도는 몸에 좋아요?','아니요 맛있어요',NULL,NULL,DEFAULT,'Y',SYSDATE,SYSDATE);
INSERT INTO FREEBOARD VALUES(SEQ_BOARD_NO.NEXTVAL,1,'요즘 핫한 유행어아세요?','어쩔티비 저쩔티비 응 삼성 QLED 티비',NULL,NULL,DEFAULT,'Y',SYSDATE,SYSDATE);
INSERT INTO FREEBOARD VALUES(SEQ_BOARD_NO.NEXTVAL,1,'여러분 힘내요 위기를 거꾸로하면','기위에요 예 아무것도 아니니까 힘내야해요',NULL,NULL,DEFAULT,'Y',SYSDATE,SYSDATE);
INSERT INTO FREEBOARD VALUES(SEQ_BOARD_NO.NEXTVAL,1,'[속보]겁나추움 옷 따듯하게 입으셈','진짜추워 너무추어 아ㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏ춥다ㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏ',NULL,NULL,DEFAULT,'Y',SYSDATE,SYSDATE);
INSERT INTO FREEBOARD VALUES(SEQ_BOARD_NO.NEXTVAL,1,'최고의 성형은','가장 비싼 성형이다',NULL,NULL,DEFAULT,'Y',SYSDATE,SYSDATE);




COMMIT;
SELECT * FROM FREEBOARD;

--------------------------------------------------------------------
------------------------- REPLY 관련 테이블 -------------------------
--------------------------------------------------------------------

DROP TABLE REPLY CASCADE CONSTRAINTS;

CREATE TABLE REPLY(
  NO NUMBER PRIMARY KEY,
  BOARD_NO NUMBER,
  WRITER_NO NUMBER,
  CONTENT VARCHAR2(400),
  STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN ('Y', 'N')),
  CREATE_DATE DATE DEFAULT SYSDATE,
  MODIFY_DATE DATE DEFAULT SYSDATE,
  FOREIGN KEY (BOARD_NO) REFERENCES FreeBOARD,
  FOREIGN KEY (WRITER_NO) REFERENCES MEMBER
);

DROP SEQUENCE SEQ_REPLY_NO;
CREATE SEQUENCE SEQ_REPLY_NO;

COMMENT ON COLUMN "REPLY"."NO" IS '댓글번호';
COMMENT ON COLUMN "REPLY"."BOARD_NO" IS '댓글이작성된게시글';
COMMENT ON COLUMN "REPLY"."WRITER_NO" IS '댓글작성자';
COMMENT ON COLUMN "REPLY"."CONTENT" IS '댓글내용';
COMMENT ON COLUMN "REPLY"."STATUS" IS '상태값(Y/N)';
COMMENT ON COLUMN "REPLY"."CREATE_DATE" IS '댓글올린날짜';
COMMENT ON COLUMN "REPLY"."MODIFY_DATE" IS '댓글수정날짜';

COMMIT;

SELECT * FROM REPLY;


BEGIN
    FOR N IN 1..10
    LOOP
        INSERT INTO REPLY VALUES(SEQ_REPLY_NO.NEXTVAL, N, 1, '안녕하세요.', DEFAULT, DEFAULT, DEFAULT);
    END LOOP;
    
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN ROLLBACK;
END;


------------------------------------------------
--------------- Member 관련 테이블 ---------------
------------------------------------------------

DROP TABLE MEMBER CASCADE CONSTRAINTS;
CREATE TABLE MEMBER (
    NO NUMBER PRIMARY KEY,
    ID VARCHAR2(50) NOT NULL UNIQUE,
    PASSWORD VARCHAR2(100) NOT NULL,
    ROLE VARCHAR2(10) DEFAULT 'ROLE_USER',
    NAME VARCHAR2(30) NOT NULL,
    EMAIL VARCHAR2(100),
    ADDRESS VARCHAR2(100),
    STATUS VARCHAR2(1) DEFAULT 'Y' CHECK(STATUS IN('Y', 'N')),
    ENROLL_DATE DATE DEFAULT SYSDATE,
    MODIFY_DATE DATE DEFAULT SYSDATE
);

DROP SEQUENCE SEQ_MEMBER;
CREATE SEQUENCE SEQ_MEMBER;

COMMENT ON COLUMN MEMBER.NO IS '회원번호';
COMMENT ON COLUMN MEMBER.ID IS '회원아이디';
COMMENT ON COLUMN MEMBER.PASSWORD IS '회원비밀번호';
COMMENT ON COLUMN MEMBER.ROLE IS '회원타입';
COMMENT ON COLUMN MEMBER.NAME IS '회원명';
COMMENT ON COLUMN MEMBER.EMAIL IS '이메일';
COMMENT ON COLUMN MEMBER.ADDRESS IS '주소';
COMMENT ON COLUMN MEMBER.STATUS IS '상태값(Y/N)';
COMMENT ON COLUMN MEMBER.ENROLL_DATE IS '회원가입일';
COMMENT ON COLUMN MEMBER.MODIFY_DATE IS '정보수정일';


INSERT INTO MEMBER (
    NO, 
    ID, 
    PASSWORD, 
    ROLE,
    NAME, 
    EMAIL, 
    ADDRESS, 
    STATUS, 
    ENROLL_DATE, 
    MODIFY_DATE
) VALUES(
    SEQ_MEMBER.NEXTVAL, 
    'admin', 
    '1234', 
    'ROLE_ADMIN', 
    '관리자', 
    'admin@iei.or.kr', 
    '서울시 강남구 역삼동',
    DEFAULT,
    DEFAULT,
    DEFAULT
);

COMMIT;

SELECT * FROM MEMBER;


DROP TABLE USERRECIPE CASCADE CONSTRAINTS;
CREATE TABLE USERRECIPE (
    HR_NO NUMBER PRIMARY KEY,
    USER_NO NUMBER,
    RCP_NM VARCHAR2(200),
    RCP_PAT2 VARCHAR2(50),
    RCP_WAY2 VARCHAR2(50),
    ATT_FILE_NO_MK VARCHAR2(900),
    RCP_PARTS_DTLS CLOB,
    FOREIGN KEY(USER_NO) REFERENCES MEMBER(NO)
);

COMMENT ON COLUMN USERRECIPE.HR_NO IS '일련번호';
COMMENT ON COLUMN USERRECIPE.USER_NO IS '회원번호';
COMMENT ON COLUMN USERRECIPE.RCP_NM IS '메뉴명';
COMMENT ON COLUMN USERRECIPE.RCP_WAY2 IS '조리방법';
COMMENT ON COLUMN USERRECIPE.ATT_FILE_NO_MK IS '이미지경로(대)';
COMMENT ON COLUMN USERRECIPE.RCP_PARTS_DTLS IS '재료정보';

DROP SEQUENCE SEQ_USERRECIPE;
CREATE SEQUENCE SEQ_USERRECIPE;

COMMIT;

DROP TABLE USERRECIPEMANUAL CASCADE CONSTRAINTS;
CREATE TABLE USERRECIPEMANUAL (
    RM_NO NUMBER PRIMARY KEY,
    HR_NO NUMBER,
    SEQ NUMBER,
    manual VARCHAR2(900),
    manualImg VARCHAR2(900),
    FOREIGN KEY(HR_NO) REFERENCES USERRECIPE(HR_NO)
);

COMMENT ON COLUMN USERRECIPEMANUAL.RM_NO IS '일련번호';
COMMENT ON COLUMN USERRECIPEMANUAL.HR_NO IS 'USERRECIPE 일련번호';
COMMENT ON COLUMN USERRECIPEMANUAL.SEQ IS '만드는 순서';
COMMENT ON COLUMN USERRECIPEMANUAL.manual IS '만드는 법';
COMMENT ON COLUMN USERRECIPEMANUAL.manualImg IS '이미지경로';

DROP SEQUENCE SEQ_USERRECIPEMANUAL;
CREATE SEQUENCE SEQ_USERRECIPEMANUAL;

COMMIT;